### ISSUE TITLE
PancakeView with HasShadow & CornerRadius

### ISSUE THREAD

**Issue by lsaudon** [sthewissen/Xamarin.Forms.PancakeView#42] opened 2019-09-10 12:56 UTC
Hello,

CornerRadius are not considered when HasShadow is True
```xml
<pancakeView:PancakeView 
    BackgroundColor="Red" 
    CornerRadius="60,10,60,10" 
    HasShadow="True"/>
```

**Comment by sthewissen** [comment] 2019-09-10 12:58
Please provide additional information such as the version number of PancakeView used. A repro product would also be appreciated. This specific scenario has been fixed in the latest version as far as I know with the introduction of completely revamped custom renderers.

**Comment by lsaudon** [comment] 2019-09-10 13:24
PancakeView: 1.1.8
Xamarin.Forms: 4.2.0.709249
On One Plus 6T API 28

```xml
        <pancakeView:PancakeView 
            BackgroundColor="Chocolate" 
            Margin="10,20" 
            HasShadow="True" 
            CornerRadius="60,10,30,20"
            VerticalOptions="FillAndExpand"
            HorizontalOptions="FillAndExpand"/>
```

**Comment by sthewissen** [comment] 2019-09-11 13:48
I see now. This seems to be a regression because it has worked in the past. I will take a look.

**Comment by sthewissen** [comment] 2019-09-24 10:51
Still somewhat confused about this one. I'm fairly sure I've seen it work but haven't figured out when this regressed just yet.

**Comment by lsaudon** [comment] 2019-09-24 10:57
Still somewhat confused about this one. I'm fairly sure I've seen it work but haven't figured out when this regressed just yet.

**Comment by sthewissen** [comment] 2019-10-06 13:18
Working on this as we speak. One thing left to fix and this should be good to go.

**Closed** 2019-10-06 15:10 UTC

**Comment by lsaudon** [comment] 2019-10-07 11:50
Hey, 
Your fix don't work well. I don't know why but if the first corner is bigger than the others it doesn't work.
```xml
            <pancakeView:PancakeView Grid.Row="1"
                                     HorizontalOptions="FillAndExpand"
                                     VerticalOptions="FillAndExpand"
                                     BackgroundColor="Blue"
                                     CornerRadius="0,50,10,40"
                                     HasShadow="True" />
            <pancakeView:PancakeView Grid.Row="2"
                                     HorizontalOptions="FillAndExpand"
                                     VerticalOptions="FillAndExpand"
                                     BackgroundColor="Blue"
                                     CornerRadius="50,0,40,10"
                                     HasShadow="True" />
```
![image](https://user-images.githubusercontent.com/25029876/66309020-d25f9380-e908-11e9-9edd-fdac88d3d2e8.png)
