### ISSUE TITLE
Cannot access a disposed object - Droid.PancakeViewRenderer

### ISSUE THREAD

**Issue by Orgbrat** [sthewissen/Xamarin.Forms.PancakeView#115] opened 2020-07-18 14:37 UTC
Have Xamarin.Forms 4.7.0.1142 (Android, iOS and UWP) and have upgraded to the latest version 2.0.1.698 of PancakeView.  I have updated the Shadow and Border properties to the new way using the Markup design method.

`            <yummy:PancakeView
                x:Name="LoginView"
                Grid.Row="1"
                Grid.Column="1"
                Margin="10,5,10,10"
                Padding="10"
                BackgroundColor="{DynamicResource BackgroundColorSecondary}"
                Border="{yummy:BorderMarkup Color={StaticResource ListItemBorderColor}, Thickness=3}"
                CornerRadius="10,10,10,10"
                Shadow="{yummy:ShadowMarkup Color=#b3b3b3,
                                      Offset='5,5'}">`

The UWP and iOS seem to be working as they should be excpected but on the Android platform I randomly get the following exception from the PancakeViewRenderer that crashes the application.

`System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'Xamarin.Forms.PancakeView.Droid.PancakeViewRenderer'.'`

Thought I would enable Source Link so I could debug the PancakeViewRenderer and give you more information but I was enable to get Source Link working . Open to helping debug this if I could get Source Link working.

Orgbrat

**Comment by sthewissen** [comment] 2020-07-19 20:45
Might be a duplicate of #112

**Comment by sthewissen** [comment] 2020-07-24 14:21
Could you try this in https://www.nuget.org/packages/Xamarin.Forms.PancakeView/2.0.1.701-beta?

**Comment by Orgbrat** [comment] 2020-07-24 15:27
@sthewissen  I tried this in Android first and it seems to be fixed or at least I tried to get errors and none happened. :)
I also tried in the UWP and iOS platforms just to make sure we were still OK in those and everything seems OK there too.
Good job...

**Closed** 2020-07-28 06:46 UTC
